#!/usr/bin/env python3
"""Generate empty stub implementations for undefined linker symbols.

Reads undefined symbol names from stdin or a file (one per line, with full
C++ signature including parameter types), and generates a .cpp file with
no-op implementations.

Usage:
    # From linker error output:
    grep "undefined reference" build.log | sed "s/.*\`//" | sed "s/'.*//" | sort -u | \
        python3 tools/gen-linker-stubs.py > src/linker_stubs_gen.cpp

    # From a file:
    python3 tools/gen-linker-stubs.py --input missing_symbols.txt --output src/linker_stubs_gen.cpp
"""

import argparse
import sys
import re


def parse_symbol(line: str) -> tuple[str, str] | None:
    """Extract function name and parameter list from a symbol line.

    Input: 'funcname(unsigned char*, R5900Context*, PS2Runtime*)'
    Output: ('funcname', 'unsigned char*, R5900Context*, PS2Runtime*')
    """
    line = line.strip()
    if not line or line.startswith('#'):
        return None

    # Find the parameter list
    paren_idx = line.find('(')
    if paren_idx < 0:
        return None

    name = line[:paren_idx]
    params = line[paren_idx:]

    # Only stub functions with the recompiled signature
    if 'R5900Context*' not in params:
        return None

    return (name, params)


def generate_stubs(symbols: list[str]) -> str:
    """Generate C++ source with empty stub implementations."""
    lines = [
        '// Auto-generated by tools/gen-linker-stubs.py',
        '// Empty stubs for functions PS2Recomp could not decompile.',
        '// These are no-ops — crash-driven development will identify which',
        '// ones need real implementations.',
        '//',
        f'// {len(symbols)} stubs generated',
        '',
        '#include "ps2_runtime.h"',
        '',
    ]

    for sym in symbols:
        parsed = parse_symbol(sym)
        if parsed is None:
            continue
        name, params = parsed
        lines.append(f'void {name}{params} {{}}')

    lines.append('')  # trailing newline
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate linker stubs')
    parser.add_argument('--input', '-i', help='Input file with symbol names')
    parser.add_argument('--output', '-o', help='Output .cpp file')
    args = parser.parse_args()

    if args.input:
        with open(args.input) as f:
            symbols = f.read().strip().split('\n')
    else:
        symbols = sys.stdin.read().strip().split('\n')

    symbols = [s for s in symbols if s.strip()]

    output = generate_stubs(symbols)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
        # Count actual stubs generated (lines starting with 'void ')
        count = sum(1 for line in output.split('\n') if line.startswith('void '))
        print(f'Generated {count} stubs in {args.output}', file=sys.stderr)
    else:
        print(output)


if __name__ == '__main__':
    main()
