#!/usr/bin/env python3
"""Generate registerAllFunctions() C++ from ps2_recompiled_functions.h.

Parses the function declarations header produced by PS2Recomp and generates
a C++ source file that registers every recompiled function with the PS2Runtime
dispatch table.

Usage:
    python3 tools/gen-register-functions.py \
        --input output/champions-of-norrath/ps2_recompiled_functions.h \
        --output src/register_functions_gen.cpp
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

# Matches: void funcName_0xHEXADDR(uint8_t* rdram, R5900Context* ctx, PS2Runtime *runtime);
_DECL_RE = re.compile(
    r"^void\s+(\w+_0x([0-9a-fA-F]+))\s*\("
)


def parse_declarations(lines: list[str]) -> list[tuple[str, int]]:
    """Extract (function_name, address) pairs from header lines.

    Only lines starting with 'void' that contain the _0xHEX pattern are parsed.
    Everything else (preprocessor, forward declarations, blanks) is skipped.
    """
    results: list[tuple[str, int]] = []
    for line in lines:
        m = _DECL_RE.match(line.strip())
        if m:
            name = m.group(1)
            addr = int(m.group(2), 16)
            results.append((name, addr))
    return results


def deduplicate(decls: list[tuple[str, int]]) -> list[tuple[str, int]]:
    """Resolve duplicate addresses, preferring named functions over entry_* stubs.

    Priority (highest to lowest):
      1. Named functions (any name not starting with 'entry_')
      2. sub_XXXX (auto-generated but still the canonical symbol)
      3. entry_XXXX (mid-function entry points from recompiler)

    Returns results sorted by address ascending.
    """
    if not decls:
        return []

    by_addr: dict[int, list[tuple[str, int]]] = {}
    for name, addr in decls:
        by_addr.setdefault(addr, []).append((name, addr))

    result: list[tuple[str, int]] = []
    for addr in sorted(by_addr.keys()):
        candidates = by_addr[addr]
        if len(candidates) == 1:
            result.append(candidates[0])
        else:
            # Prefer non-entry_ candidates
            non_entry = [c for c in candidates if not c[0].startswith("entry_")]
            if non_entry:
                # Among non-entry, prefer named over sub_
                named = [c for c in non_entry if not c[0].startswith("sub_")]
                result.append(named[0] if named else non_entry[0])
            else:
                # All are entry_ -- take the first one
                result.append(candidates[0])

    return result


def generate_cpp(decls: list[tuple[str, int]]) -> str:
    """Generate C++ source with registerAllFunctions() body.

    Args:
        decls: Deduplicated list of (function_name, address) pairs, sorted by address.

    Returns:
        Complete C++ source file as a string.
    """
    lines: list[str] = []
    lines.append("// Auto-generated by tools/gen-register-functions.py")
    lines.append(f"// {len(decls)} functions registered")
    lines.append("")
    lines.append('#include "register_functions.h"')
    lines.append('#include "ps2_runtime.h"')
    lines.append('#include "ps2_recompiled_functions.h"')
    lines.append("")
    lines.append("void registerAllFunctions(PS2Runtime &runtime)")
    lines.append("{")

    for name, addr in decls:
        lines.append(f"    runtime.registerFunction(0x{addr:08x}, {name});")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate registerAllFunctions() C++ from PS2Recomp header"
    )
    parser.add_argument(
        "--input", "-i",
        type=Path,
        default=Path("output/champions-of-norrath/ps2_recompiled_functions.h"),
        help="Path to ps2_recompiled_functions.h",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=Path("src/register_functions_gen.cpp"),
        help="Output path for generated C++ file",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    with open(args.input, "r") as f:
        header_lines = f.readlines()

    decls = parse_declarations(header_lines)
    deduped = deduplicate(decls)
    cpp_code = generate_cpp(deduped)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        f.write(cpp_code)

    print(f"Generated {args.output}: {len(deduped)} functions "
          f"({len(decls)} declarations, {len(decls) - len(deduped)} duplicates removed)")


if __name__ == "__main__":
    main()
