#!/usr/bin/env python3
"""Generate ps2_recompiled_stubs.h from PS2Recomp output.

Reads ps2_recompiled_functions.h to get all function declarations, scans .cpp
files to identify stubs (those that don't include ps2_recompiled_stubs.h), and
generates a header with forward declarations for stub functions only.

Usage:
    python3 tools/gen-recomp-stubs.py [output_dir]

    output_dir defaults to output/champions-of-norrath/
"""

import re
import sys
from pathlib import Path

# Pattern to match function declarations like:
# void funcname_0xADDR(uint8_t* rdram, R5900Context* ctx, PS2Runtime *runtime);
DECL_RE = re.compile(
    r"^void\s+(\w+_0x[0-9a-fA-F]+)\s*\("
)

# Pattern to extract hex address from function name
ADDR_RE = re.compile(r"_0x([0-9a-fA-F]+)$")

# The include line that distinguishes decompiled files from stubs
STUBS_INCLUDE = 'ps2_recompiled_stubs.h'


def parse_declarations(header_path: Path) -> list[dict]:
    """Parse function declarations from ps2_recompiled_functions.h.

    Returns a list of dicts with keys:
        - name: function name (e.g. 'abort_0x2ff8c0')
        - line: full declaration line (e.g. 'void abort_0x2ff8c0(...);')
        - addr: integer address extracted from the name
    """
    declarations = []
    text = header_path.read_text()
    for line in text.splitlines():
        line = line.strip()
        m = DECL_RE.match(line)
        if m:
            func_name = m.group(1)
            addr_m = ADDR_RE.search(func_name)
            addr = int(addr_m.group(1), 16) if addr_m else 0
            declarations.append({
                "name": func_name,
                "line": line,
                "addr": addr,
            })
    return declarations


def identify_stub_files(output_dir: Path) -> list[dict]:
    """Identify stub .cpp files in the output directory.

    A stub file is one that does NOT include ps2_recompiled_stubs.h.
    This is the distinguishing feature: fully-decompiled files include it,
    stubs don't.

    Returns a list of dicts with keys:
        - path: Path to the .cpp file
        - func_name: function name derived from filename (minus .cpp)
    """
    stubs = []
    for cpp_path in sorted(output_dir.glob("*.cpp")):
        # Read just the first ~10 lines to check includes (more efficient
        # than reading the entire file for large decompiled files)
        with open(cpp_path) as f:
            head = ""
            for i, line in enumerate(f):
                if i >= 15:
                    break
                head += line

        if STUBS_INCLUDE not in head:
            func_name = cpp_path.stem
            stubs.append({
                "path": cpp_path,
                "func_name": func_name,
            })
    return stubs


def generate_header(declarations: list[dict], stub_names: set[str]) -> str:
    """Generate the ps2_recompiled_stubs.h header content.

    Args:
        declarations: All declarations from ps2_recompiled_functions.h
        stub_names: Set of function names that are stubs

    Returns:
        Header file content as a string.
    """
    # Filter to only stub declarations and sort by address
    stub_decls = [d for d in declarations if d["name"] in stub_names]
    stub_decls.sort(key=lambda d: d["addr"])

    lines = [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "struct R5900Context;",
        "class PS2Runtime;",
        "",
        "// Forward declarations for stub functions",
        f"// Generated by tools/gen-recomp-stubs.py ({len(stub_decls)} stubs)",
        "",
    ]

    for decl in stub_decls:
        lines.append(decl["line"])

    lines.append("")  # trailing newline
    return "\n".join(lines)


def generate_stubs_header(output_dir: Path) -> Path:
    """Full pipeline: scan directory, generate header, write file.

    Args:
        output_dir: Path to the PS2Recomp output directory.

    Returns:
        Path to the generated header file.
    """
    header_path = output_dir / "ps2_recompiled_functions.h"
    if not header_path.exists():
        raise FileNotFoundError(f"Functions header not found: {header_path}")

    declarations = parse_declarations(header_path)
    stubs = identify_stub_files(output_dir)
    stub_names = {s["func_name"] for s in stubs}

    content = generate_header(declarations, stub_names)

    out_path = output_dir / "ps2_recompiled_stubs.h"
    out_path.write_text(content)

    return out_path


def main():
    if len(sys.argv) > 1:
        output_dir = Path(sys.argv[1])
    else:
        output_dir = Path(__file__).parent.parent / "output" / "champions-of-norrath"

    if not output_dir.is_dir():
        print(f"Error: {output_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    out_path = generate_stubs_header(output_dir)

    # Report stats
    declarations = parse_declarations(output_dir / "ps2_recompiled_functions.h")
    stubs = identify_stub_files(output_dir)
    print(f"Total declarations in functions header: {len(declarations)}")
    print(f"Stub files identified: {len(stubs)}")
    print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
